### ISSUE TITLE
TypeError when caching is not being used.

### ISSUE THREAD

**Issue by kadams54** [switchboardpy/switchboard#8]
From the logs

~~~~
From the logs :

ERROR:switchboard.manager:Error checking if switch "masthead-2nd-gen" is active
Traceback (most recent call last):
File "/srv/blues_browser-jc-blues-browser/blues_browser/local/lib/python2.7/site-packages/switchboard/manager.py", line 123, in is_active
switch = self[key]
File "/srv/blues_browser-jc-blues-browser/blues_browser/local/lib/python2.7/site-packages/switchboard/manager.py", line 97, in __getitem__
return SwitchProxy(self, super(SwitchManager, self).__getitem__(key))
File "/srv/blues_browser-jc-blues-browser/blues_browser/local/lib/python2.7/site-packages/switchboard/base.py", line 35, in __getitem__
return self._cache[key]
TypeError: 'NoneType' object has no attribute '__getitem__'
~~~~

**Comment by kadams54** [comment]
I suspect the problem is related to the change awhile back to make caching optional. It looks like there's still some code that assumes a cache is present.

**Comment by kadams54** [comment]
Added more logging to find out exactly why this is happening.
